### ISSUE TITLE
Evaluate values that should be converted to environment variables with default values

### ISSUE THREAD

**Issue by AevumDecessus** [fragforce/fragforce.org#124]
Example: cron values in fragforce/cron.py

**Comment by gpmidi** [comment]
Added two more in 03659c86ff34413e490e8ec6dddc19369d88c40a

**Comment by gpmidi** [comment]
What about "page.meta['youtube_id'] = page.meta.get('youtube_id', choice(['ZS7WRl7N1Ig', 'wp2ORytO1F4', 'kaUPEdwjWyg']))"
